version: "3.7"
services:

  mongo:
    restart: always
    image: mongo
    ports:
      - "27017"

  todo-backend: 
    image: mombe090/todo-go-backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8090:8090"
